### ISSUE TITLE
Bookings: Allow recurring bookings, with enforced rules from Zone Metadata

### ISSUE THREAD

**Issue by w-le** [PlaceOS/staff-api#12] opened 2020-12-07 13:12 UTC
Bookings (e.g. desk bookings) should support recurrence in the same way that Events do.

Optional Rules relating to recurrence (like max recurrences, max days in the future) should be definable from Zone metadata and apply to roles/groups of users - similar to Event booking rules.

**Comment by caspiano** [comment] 2022-02-02 02:13
Duplicate of #141

**Closed as completed by caspiano** 2022-02-02 02:13 UTC
Labels: type: enhancement
